sudo: required

dist: Xenial

addons:
  sonarqube: true

jdk:
  - oraclejdk8

before_install: 
  - if [ $TRAVIS_OS_NAME == "linux" ]; then 
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
  - wget -O os.deb http://oscript.io/downloads/1_0_18/onescript-engine_1.0.18_all.deb
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/ubuntu xenial main" | sudo tee /etc/apt/sources.list.d/mono-official.list
  - sudo apt-get update
  - sudo apt-get mono-complete ca-certificates-mono libmono-i18n4.0-all mono-runtime mono-mcs
  - sudo dpkg -i os.deb; sudo apt install -f
  - sudo oscript /usr/share/oscript/lib/opm/src/opm.os install opm
  - oscript

install: 
  - sudo oscript /usr/share/oscript/lib/opm/src/opm.os install 1testrunner
  - sudo oscript /usr/share/oscript/lib/opm/src/opm.os install 1bdd
  - sudo oscript /usr/share/oscript/lib/opm/src/opm.os install
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
- ./travis.sh 